name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Expose Neon to the whole job (ensure you created the secret)
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # Optional: speed up Prisma generators in CI
      PRISMA_SKIP_POSTINSTALL_GENERATE: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      # (Optional) If you prefer .env files in CI, uncomment this block
      # - name: Create .env from secrets
      #   run: |
      #     printf 'DATABASE_URL="%s"\n' "${{ secrets.DATABASE_URL }}" > .env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Build project
        run: pnpm build
