name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Use Corepack to install/activate pnpm on the runner
      - name: Enable Corepack & prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Push Prisma schema (ephemeral SQLite)
        env:
          DATABASE_URL: "file:./dev.db"
        run: pnpm db:push

      - name: Build
        env:
          JWT_SECRET: "dev-only-secret"
          NEXT_TELEMETRY_DISABLED: "1"
        run: pnpm build
